// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication2.Data;

namespace WebApplication2.Migrations
{
    [DbContext(typeof(MoviesContext))]
    partial class MoviesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("WebApplication2.Models.Movies.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Poster")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Author = "Todd Phillips",
                            CreatedAt = new DateTime(2019, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Crime , Drama , Thriller",
                            Name = "Joker",
                            Poster = "https://www.kinopoisk.ru/images/film_big/1048334.jpg"
                        },
                        new
                        {
                            Id = -2,
                            Author = "David Leitch",
                            CreatedAt = new DateTime(2019, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Action , Adventure",
                            Name = "Fast & Furious Presents: Hobbs & Shaw",
                            Poster = "https://m.media-amazon.com/images/I/A1nD1zDE9pL._SS500_.jpg"
                        },
                        new
                        {
                            Id = -3,
                            Author = "Jon Favreau",
                            CreatedAt = new DateTime(2019, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Adventure , Animation , Drama , Family , Musical",
                            Name = "The Lion King",
                            Poster = "https://images-na.ssl-images-amazon.com/images/I/91kXw97IUBL._AC_SL1500_.jpg"
                        },
                        new
                        {
                            Id = -4,
                            Author = "Joachim Rønning",
                            CreatedAt = new DateTime(2019, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Adventure , Family , Fantasy",
                            Name = "Maleficent: Mistress of Evil",
                            Poster = "https://st.kp.yandex.net/images/film_iphone/iphone360_916498.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
